### ISSUE TITLE
Do dependencies work?

### ISSUE THREAD

**Issue by gitkodak** [ghoneycutt/puppet-module-types#31]
I'm trying to add dependencies through hiera.

For example:
`types::files:                                                                                                            
  /opt/peoplesoftfs/install:                                                                                             
    ensure: directory                                                                                                    
    owner: psfsadm1                                                                                                      
    group: uxp_peoplesoftfs_app_admin_d                                                                                  
    mode: '0775'                                                                                                         
    #before:  Types::mounts[/opt/peoplesoftfs/install]                                                                    
                                                          
types::mounts:                                                                                                           
                                                                          
  /opt/peoplesoftfs/install:                                                                                             
   device: nfssvr:/vol/peoplesoftfs/install_d                                                                   
   fstype: nfs                                                                                                           
   options: soft,intr,rsize=8192,wsize=8192                                                                              
   require: Types::files[/opt/peoplesoft/install]`

But I get:

Error: Failed to apply catalog: Could not find dependency Types::Files[/opt/peoplesoft/install] for Types::Mount[/opt/peoplesoftfs/install]

If I reverse it (comment out the require, uncomment the before) it doesn't complain, but it doesn't appear to do anything either.

Is this supported?  If not, any suggestions for how to do it?  Just let it fail if it tries to mount before the directories are created?

**Comment by ghoneycutt** [comment]
try this, as the resource you want is a file.

``` yaml
require: 'File[/opt/peoplesoft/install]'
```

**Comment by gitkodak** [comment]
This is my putting my face in my palm.

Thanks.

**Comment by ghoneycutt** [comment]
No worries, took me a bit the first time with these, too :)
