### ISSUE TITLE
Dependency on common-1.6.0, but it does not exist in the forge

### ISSUE THREAD

**Issue by phlantin** [ghoneycutt/puppet-module-types#37]
common-1.6.0 is listed as a dependency on your latest version, but it hasn't been updated in the forge.

**Comment by ghoneycutt** [comment]
Suggest using github in your Puppetfile instead of the forge, as github is more likely to be available.

Thanks for pointing this out! I've put it up there.

https://forge.puppet.com/ghoneycutt/common/1.6.0

**Comment by phlantin** [comment]
Thank you!

On May 25, 2016, at 1:39 PM, Garrett Honeycutt <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #37<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ghoneycutt_puppet-2Dmodule-2Dtypes_issues_37&d=DQMCaQ&c=N13-TaG7c-EYAiUNohBk74oLRjUiBTwVm-KSnr4bPSc&r=B5PyX-m5i2WHoi0BT-2P8nCox7f1Ko9Ku23W9-m-Wq0&m=rOqG1YRGkZYIr6W8xx8GFWhf0SsCQEpeU85r9YSA0Rw&s=ydsPI26sKCaw7yLQNfyKmG8IhxJ3n0P27LSrJAS2bqs&e=>.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ghoneycutt_puppet-2Dmodule-2Dtypes_issues_37-23event-2D672345647&d=DQMCaQ&c=N13-TaG7c-EYAiUNohBk74oLRjUiBTwVm-KSnr4bPSc&r=B5PyX-m5i2WHoi0BT-2P8nCox7f1Ko9Ku23W9-m-Wq0&m=rOqG1YRGkZYIr6W8xx8GFWhf0SsCQEpeU85r9YSA0Rw&s=k4ohBzDU20ngD-EZGJAtYyPIyFcpQIDpTe-a8LHdoG0&e=>

----------------------------------------------------------------------
This message and any attachments are intended only for the use of the addressee and may contain information that is privileged and confidential. If the reader of the message is not the intended recipient or an authorized representative of the intended recipient, you are hereby notified that any dissemination of this communication is strictly prohibited. If you have received this communication in error, notify the sender immediately by return email and delete the message and any attachments from your system.
