### ISSUE TITLE
Cannot resolve dependency as `ghoneycutt-common 1.7.0` is not released 

### ISSUE THREAD

**Issue by patrickli** [ghoneycutt/puppet-module-types#44]
Trying to install `ghoneycutt-types >= 1.11.0` will result in "Could not resolve the dependencies." since it depends on `ghoneycutt-common 1.7.0` but the latest version on puppetforge is `1.6.0`.

Please update `ghoneycutt-common` on puppetforge.

**Comment by ghoneycutt** [comment]
I use https://github.com/bodepd/librarian-puppet-simple and r10k and sometimes miss releases to the forge.  Thanks for pointing this out to me. It is much appreciated.

ghoneycutt/common v1.7.0 is up on the forge
